# Generated by Django 5.1.1 on 2024-09-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
