# Generated by Django 5.1.1 on 2024-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecheck',
            name='status_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='machinecheck',
            name='status_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
