# Generated by Django 5.1.1 on 2024-09-22 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_is_admin_chatlog_supportrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='admin',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='support_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='users.supportrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
