# Generated by Django 5.1.1 on 2024-09-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_user_chatlog_sender_remove_chatlog_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to='users.user'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='users.user'),
        ),
    ]
